### ISSUE TITLE
[JENKINS-61978] AD user not able to login using Active Directory plugin

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/active-directory-plugin#595]
<p>For most users the AD plugin is working well.  However for one user on the domain, all login attempts are being refused because of incorrect password.  The password he is using is, however, the correct one and is the one used to login to all other resources on the network.  It is uniquely with the Jenkins server that the problem occurs.</p>

<p> </p>

<p>Looking at the logs (full output below)  for all users that succeed in logging in I see this kind of entry:</p>

<p><UserADShortName> dn=CN=<FirstName LastName>,OU=<CompanyName>,OU=Services,OU=<OfficeLocation>,OU=Locations,DC=misys,DC=global,DC=ad</p>

<p> </p>

<p>but for the case of this one user, and only this user, the dn is in upper case:</p>

<p>Login failure: Incorrect password for <shortname> DN=CN=<FirstName LastName>,OU=<CompanyName>,OU=Users,OU=<OfficeLocation>,OU=Locations,DC=misys,DC=global,DC=ad</p>

<p>The only difference at this level appears to be that "DN" is in upper case.  This is probably just a quirk in the error logging.</p>

<p>One difference about his name that may be salient is that it contains a cedilla.</p>

<p>A recent forced flush and reassignment of all user passwords was implemented across the company, the user could log in prior to that event but now, even after changing his password, login is not possible for the user.</p>

<p> </p>

<p>The issue replicates for this user using different Jenkins server instances (same version of Jenkins plus plug in).  It also replicates no matter which workstation the user attempts to login from (his own or someone else's).  Full error log is as follows:</p>

<p> </p>

<p>Login failure: Incorrect password for <shortname replaced> DN=CN=<FirstNaem LastName>,OU=<CompanyName>,OU=Users,OU=<OfficeLocation>,OU=Locations,DC=<CompanyName>,DC=global,DC=ad: error=8007052E<br/>
com4j.ComException: 8007052e The user name or password is incorrect. : The user name or password is incorrect.<br/>
 : .\invoke.cpp:517<br/>
 at com4j.Native.invoke(Native Method)<br/>
 at com4j.StandardComMethod.invoke(StandardComMethod.java:35)<br/>
 at com4j.Wrapper$InvocationThunk.call(Wrapper.java:356)<br/>
 at com4j.Task.invoke(Task.java:50)<br/>
 at com4j.ComThread.run0(ComThread.java:172)<br/>
 at com4j.ComThread.run(ComThread.java:153)<br/>
Caused: com4j.ComException: 8007052e The user name or password is incorrect. : The user name or password is incorrect.<br/>
 : .\invoke.cpp:517<br/>
 at com4j.Wrapper.invoke(Wrapper.java:187)<br/>
 at com.sun.proxy.$Proxy116.openDSObject(Unknown Source)<br/>
 at hudson.plugins.active_directory.ActiveDirectoryAuthenticationProvider$1.call(ActiveDirectoryAuthenticationProvider.java:166)<br/>
 at hudson.plugins.active_directory.ActiveDirectoryAuthenticationProvider$1.call(ActiveDirectoryAuthenticationProvider.java:142)<br/>
 at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4767)<br/>
 at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)<br/>
 at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)<br/>
 at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)<br/>
 at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)<br/>
 at com.google.common.cache.LocalCache.get(LocalCache.java:3965)<br/>
 at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4764)<br/>
 at hudson.plugins.active_directory.ActiveDirectoryAuthenticationProvider.retrieveUser(ActiveDirectoryAuthenticationProvider.java:142)<br/>
 at org.acegisecurity.providers.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:122)<br/>
 at org.acegisecurity.providers.ProviderManager.doAuthentication(ProviderManager.java:200)<br/>
 at org.acegisecurity.AbstractAuthenticationManager.authenticate(AbstractAuthenticationManager.java:47)<br/>
 at org.acegisecurity.ui.webapp.AuthenticationProcessingFilter.attemptAuthentication(AuthenticationProcessingFilter.java:74)<br/>
 at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:252)<br/>
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
 at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)<br/>
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
 at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)<br/>
 at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)<br/>
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
 at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)<br/>
 at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)<br/>
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br/>
 at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)<br/>
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br/>
 at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)<br/>
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br/>
 at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)<br/>
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)<br/>
 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)<br/>
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)<br/>
 at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)<br/>
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)<br/>
 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)<br/>
 at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)<br/>
 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)<br/>
 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)<br/>
 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)<br/>
 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)<br/>
 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)<br/>
 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)<br/>
 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)<br/>
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)<br/>
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)<br/>
 at org.eclipse.jetty.server.Server.handle(Server.java:505)<br/>
 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)<br/>
 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)<br/>
 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)<br/>
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)<br/>
 at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)<br/>
 at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)<br/>
 at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)<br/>
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)<br/>
 at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)<br/>
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)<br/>
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)<br/>
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)<br/>
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)<br/>
 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)<br/>
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)<br/>
 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)<br/>
 at java.lang.Thread.run(Unknown Source)<br/>
 </p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jkg20_ou">jkg20_ou</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-61978" target="_blank">AD user not able to login using Active Directory plugin</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/fbelzunc.png" title="fbelzunc's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fbelzunc">fbelzunc</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>component(s)</b>: active-directory-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-12-07
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>For most users the AD plugin is working well.  However for one user on the domain, all login attempts are being refused because of incorrect password.  The password he is using is, however, the correct one and is the one used to login to all other resources on the network.  It is uniquely with the Jenkins server that the problem occurs.</p>

<p> </p>

<p>Looking at the logs (full output below)  for all users that succeed in logging in I see this kind of entry:</p>

<p>&lt;UserADShortName&gt; dn=CN=&lt;FirstName LastName&gt;,OU=&lt;CompanyName&gt;,OU=Services,OU=&lt;OfficeLocation&gt;,OU=Locations,DC=misys,DC=global,DC=ad</p>

<p> </p>

<p>but for the case of this one user, and only this user, the dn is in upper case:</p>

<p>Login failure: Incorrect password for &lt;shortname&gt; DN=CN=&lt;FirstName LastName&gt;,OU=&lt;CompanyName&gt;,OU=Users,OU=&lt;OfficeLocation&gt;,OU=Locations,DC=misys,DC=global,DC=ad</p>

<p>The only difference at this level appears to be that "DN" is in upper case.  This is probably just a quirk in the error logging.</p>

<p>One difference about his name that may be salient is that it contains a cedilla.</p>

<p>A recent forced flush and reassignment of all user passwords was implemented across the company, the user could log in prior to that event but now, even after changing his password, login is not possible for the user.</p>

<p> </p>

<p>The issue replicates for this user using different Jenkins server instances (same version of Jenkins plus plug in).  It also replicates no matter which workstation the user attempts to login from (his own or someone else's).  Full error log is as follows:</p>

<p> </p>

<p>Login failure: Incorrect password for &lt;shortname replaced&gt; DN=CN=&lt;FirstNaem LastName&gt;,OU=&lt;CompanyName&gt;,OU=Users,OU=&lt;OfficeLocation&gt;,OU=Locations,DC=&lt;CompanyName&gt;,DC=global,DC=ad: error=8007052E
com4j.ComException: 8007052e The user name or password is incorrect. : The user name or password is incorrect.
 : .\invoke.cpp:517
 at com4j.Native.invoke(Native Method)
 at com4j.StandardComMethod.invoke(StandardComMethod.java:35)
 at com4j.Wrapper$InvocationThunk.call(Wrapper.java:356)
 at com4j.Task.invoke(Task.java:50)
 at com4j.ComThread.run0(ComThread.java:172)
 at com4j.ComThread.run(ComThread.java:153)
Caused: com4j.ComException: 8007052e The user name or password is incorrect. : The user name or password is incorrect.
 : .\invoke.cpp:517
 at com4j.Wrapper.invoke(Wrapper.java:187)
 at com.sun.proxy.$Proxy116.openDSObject(Unknown Source)
 at hudson.plugins.active_directory.ActiveDirectoryAuthenticationProvider$1.call(ActiveDirectoryAuthenticationProvider.java:166)
 at hudson.plugins.active_directory.ActiveDirectoryAuthenticationProvider$1.call(ActiveDirectoryAuthenticationProvider.java:142)
 at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4767)
 at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)
 at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)
 at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
 at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
 at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
 at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4764)
 at hudson.plugins.active_directory.ActiveDirectoryAuthenticationProvider.retrieveUser(ActiveDirectoryAuthenticationProvider.java:142)
 at org.acegisecurity.providers.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:122)
 at org.acegisecurity.providers.ProviderManager.doAuthentication(ProviderManager.java:200)
 at org.acegisecurity.AbstractAuthenticationManager.authenticate(AbstractAuthenticationManager.java:47)
 at org.acegisecurity.ui.webapp.AuthenticationProcessingFilter.attemptAuthentication(AuthenticationProcessingFilter.java:74)
 at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:252)
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
 at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
 at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
 at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
 at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
 at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
 at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
 at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
 at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
 at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
 at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
 at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
 at org.eclipse.jetty.server.Server.handle(Server.java:505)
 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
 at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
 at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
 at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
 at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
 at java.lang.Thread.run(Unknown Source)
 </p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 2.190.2<br/>
AD plugin version 2.16<br/>
Server running on Windows 2012 server
```
</details>

**Comment by HeidiRechekWork** [comment]
We just had this issue and found that the user was expired in active directory. that was not visible in Entra. You have to look in users and computers or with powershell 

PS C:\> get-aduser <SAM account name> -Properties accountexpirationdate
